### ISSUE TITLE
Error tailwind.css in uilib

### ISSUE THREAD

**Issue by BlastingLeaves** [vladblindu/uilib#1]
.uilib/css/tailwind.css does not exist.

![Screenshot 2020-05-27 at 13 02 38](https://user-images.githubusercontent.com/61146175/83006104-627a5680-a01a-11ea-8521-c8c63452b87b.png)

**Comment by vladblindu** [comment]
Fixed in commit b3360a64c9e1574d47d83d53e84d446f3b75d553
